name: Test package

description: Test one of the packages in this monorepo.

inputs:
  package_name:
    description: The name of the tested package
    required: true

runs:
  using: composite
  steps:
    - name: Install Playwright
      if: ${{ inputs.package_name == 'scratch-render' }}
      shell: bash
      run: npx playwright install --with-deps chromium
    - name: Test
      working-directory: ./packages/${{ inputs.package_name }}
      shell: bash
      env:
        TAP_REPORTER: "junit"
        TAP_REPORTER_FILE: "test-results/junit.xml"
      run: |
        mkdir -p test-results
        npm run test
    - name: Publish test reports
      if: ${{ !cancelled() }}
      uses: EnricoMi/publish-unit-test-result-action@34d7c956a59aed1bfebf31df77b8de55db9bbaaf # v2
      with:
        files: "./packages/${{ inputs.package_name }}/test-results/**/*"
        check_name: "Test report for ${{ inputs.package_name }}"
        test_file_prefix: "+packages/${{ inputs.package_name }}/"
    - name: Store Test Results
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
      with:
        name: ${{ inputs.package_name }}-test-output
        path: ./packages/${{ inputs.package_name }}/test-results/*
