name: Test Packages

on:
  workflow_call:
    inputs:
      packages:
        description: 'JSON array of package names to test'
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(inputs.packages) }}
    name: Test ${{ matrix.package }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - uses: ./.github/actions/install-dependencies
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: build
          path: packages
      - uses: ./.github/actions/test-package
        with:
          package_name: ${{ matrix.package }}

  results:
    name: Test Results
    runs-on: ubuntu-latest
    needs: test
    if: ${{ !cancelled() }}
    steps:
      - run: |
          case "${{ needs.test.result }}" in
            success)
              echo "Tests passed successfully."
              exit 0
              ;;
            cancelled)
              echo "Tests were cancelled."
              exit 1
              ;;
            *)
              echo "Tests failed. Result: ${{ needs.test.result }}"
              exit 1
              ;;
          esac
