export default MotionLog;
declare namespace MotionLog {
    /**
     * @param {string} filename
     * @return {Function}
     */
    function createLog(filename: string): Function;
    /**
     * Simple strategy to get data from browser without any saving; we'll log to the console with a unique prefix
     * to later be manually saved to file and loaded with loadConsoleLog
     *
     * @param {string} prefix
     * @return {Function}
     */
    function createConsoleLog(prefix: string): Function;
    /**
     * @param {string} filename
     * @param {Function} cb
     */
    function loadLog(filename: string, cb: Function): void;
    /**
     * Reads in a file saved from the a console log generated by createConsoleLog
     * @param {string} filename
     * @param {string} prefix
     * @param {Function} cb
     */
    function loadConsoleLog(filename: string, prefix: string, cb: Function): void;
}
