name: Build and Deploy
on: [push]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.8.0]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: pnpm/action-setup@v4
      with:
        version: 9.1.2
    - name: Install subpackage dependencies
      run: |
        for pkg in scratch-packages/scratch-editor/packages/scratch-gui scratch-packages/scratch-editor/packages/scratch-vm; do
          echo "Installing $pkg..."
          (cd $pkg && npm install --ignore-scripts)
        done
    - name: install & build
      run: pnpm install --frozen-lockfile && pnpm transpile:vm && pnpm build:extensions:and:gui --include all --watch false --parrallel false
      env:
        CI: true
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build # The folder the action should deploy.
        target-folder: ${{ steps.extract_branch.outputs.branch }}
